In [2]:
import numpy as np

In [3]:
minha_lista = [1, 2, 3]

In [5]:
minha_lista

[1, 2, 3]

In [7]:
np.array(minha_lista)

array([1, 2, 3])

In [9]:
minha_matrix = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]

In [11]:
np.array(minha_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
arr = np.zeros(3)

In [25]:
arr

array([0., 0., 0.])

In [27]:
arr = np.zeros((5, 5))

In [29]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones(3)

array([1., 1., 1.])

In [37]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.linspace(0, 10, 5) #Números igualmente espaçados

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.random.rand(5) #Sempre entre zero e 1

array([0.46008922, 0.53229745, 0.58760769, 0.5841321 , 0.37217295])

In [45]:
np.random.rand(5)*100

array([25.54527895, 78.98668642, 38.55565822, 78.29136936, 71.63655809])

In [48]:
np.random.rand(5, 4)

array([[0.59492113, 0.1382239 , 0.32556543, 0.70787723],
       [0.48444037, 0.78698671, 0.20944547, 0.01772848],
       [0.78085371, 0.33174975, 0.48790013, 0.84536452],
       [0.36236287, 0.6859143 , 0.19640472, 0.51852934],
       [0.83011073, 0.84984188, 0.66692683, 0.66554029]])

In [66]:
np.random.rand(5) #Média zero e desvio padrão 1

array([0.56518042, 0.00652696, 0.36785773, 0.05135271, 0.34278243])

In [65]:
np.random.randint(0, 100, 10) #O último parâmetro é a quantidade de números

array([37, 90, 64,  4, 21, 87, 44, 90, 25, 94])

In [68]:
np.random.rand(5)*100

array([83.22737513, 61.76397637, 40.53365368, 57.51872794, 10.01073772])

In [72]:
np.round(np.random.rand(5)*100, 0)#Último parâmetros é a quantidade e casas decimais

array([18., 16., 93., 98., 69.])

In [74]:
arr = np.random.rand(25) #Cria 25 elementos entre o e 1

In [76]:
arr

array([0.24359837, 0.22071845, 0.10953447, 0.10936319, 0.91882825,
       0.56496686, 0.66474836, 0.69557649, 0.51992875, 0.46171699,
       0.04276588, 0.21486774, 0.3528215 , 0.92762813, 0.05579435,
       0.68708442, 0.92185169, 0.30946454, 0.67781601, 0.35911602,
       0.88286102, 0.69262583, 0.69424267, 0.48075858, 0.17226383])

In [78]:
arr.reshape((5, 5)) #Vira uma matrix de 5 x 5

array([[0.24359837, 0.22071845, 0.10953447, 0.10936319, 0.91882825],
       [0.56496686, 0.66474836, 0.69557649, 0.51992875, 0.46171699],
       [0.04276588, 0.21486774, 0.3528215 , 0.92762813, 0.05579435],
       [0.68708442, 0.92185169, 0.30946454, 0.67781601, 0.35911602],
       [0.88286102, 0.69262583, 0.69424267, 0.48075858, 0.17226383]])

In [82]:
arr = arr.reshape((5, 5))

In [84]:
arr

array([[0.24359837, 0.22071845, 0.10953447, 0.10936319, 0.91882825],
       [0.56496686, 0.66474836, 0.69557649, 0.51992875, 0.46171699],
       [0.04276588, 0.21486774, 0.3528215 , 0.92762813, 0.05579435],
       [0.68708442, 0.92185169, 0.30946454, 0.67781601, 0.35911602],
       [0.88286102, 0.69262583, 0.69424267, 0.48075858, 0.17226383]])

In [86]:
arr.shape

(5, 5)

In [88]:
arr.max()

0.9276281307671037

In [90]:
arr.min()

0.04276587645365093

In [92]:
arr.argmax() #Índice na qual o maior elemento se encontra.

13

In [94]:
arr.argmin() #Índice na qual o menor elemento se encontra.

10